src/Entity/Recrutements.php
<?php

namespace App\Entity;

use App\Repository\RecrutementsRepository;
use App\Entity\Traits\Timestampable;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=RecrutementsRepository::class)
 * @ORM\HasLifecycleCallbacks
 */
class Recrutements
{
    use Timestampable;
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $NomClient;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $PrenomClient;

    /**
     * @ORM\Column(type="text")
     */
    private $AdresseClient;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $PhoneClient;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $OptionF;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $NbrMoisOF;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Reference;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Formule;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $NbrMois;

    /**
     * @ORM\Column(type="boolean")
     */
    private $Statut;

    /**
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="recrutements")
     */
    private $user;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $FinRea;

    /**
     * @ORM\Column(type="float")
     */
    private $Montant;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomClient(): ?string
    {
        return $this->NomClient;
    }

    public function setNomClient(string $NomClient): self
    {
        $this->NomClient = $NomClient;

        return $this;
    }

    public function getPrenomClient(): ?string
    {
        return $this->PrenomClient;
    }

    public function setPrenomClient(string $PrenomClient): self
    {
        $this->PrenomClient = $PrenomClient;

        return $this;
    }

    public function getAdresseClient(): ?string
    {
        return $this->AdresseClient;
    }

    public function setAdresseClient(string $AdresseClient): self
    {
        $this->AdresseClient = $AdresseClient;

        return $this;
    }

    public function getPhoneClient(): ?string
    {
        return $this->PhoneClient;
    }

    public function setPhoneClient(string $PhoneClient): self
    {
        $this->PhoneClient = $PhoneClient;

        return $this;
    }

    public function getOptionF(): ?string
    {
        return $this->OptionF;
    }

    public function setOptionF(?string $OptionF): self
    {
        $this->OptionF = $OptionF;

        return $this;
    }

    public function getNbrMoisOF(): ?int
    {
        return $this->NbrMoisOF;
    }

    public function setNbrMoisOF(?int $NbrMoisOF): self
    {
        $this->NbrMoisOF = $NbrMoisOF;

        return $this;
    }

    public function getReference(): ?string
    {
        return $this->Reference;
    }

    public function setReference(string $Reference): self
    {
        $this->Reference = $Reference;

        return $this;
    }

    public function getFormule(): ?string
    {
        return $this->Formule;
    }

    public function setFormule(string $Formule): self
    {
        $this->Formule = $Formule;

        return $this;
    }

    public function getNbrMois(): ?int
    {
        return $this->NbrMois;
    }

    public function setNbrMois(int $NbrMois): self
    {
        $this->NbrMois = $NbrMois;

        return $this;
    }

    public function getStatut(): ?int
    {
        return $this->Statut;
    }

    public function setStatut(int $Statut): self
    {
        $this->Statut = $Statut;

        return $this;
    }

    public function getUser(): ?Users
    {
        return $this->user;
    }

    public function setUser(?Users $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getFinRea(): ?\DateTimeInterface
    {
        return $this->FinRea;
    }

    public function setFinRea(\DateTimeInterface $FinRea): self
    {
        $this->FinRea = $FinRea;

        return $this;
    }

    public function getMontant(): ?float
    {
        return $this->Montant;
    }

    public function setMontant(float $Montant): self
    {
        $this->Montant = $Montant;

        return $this;
    }
}

src/Form/RecrutementsType.php
<?php

namespace App\Form;

use App\Entity\Recrutements;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RecrutementsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('NomClient')
            ->add('PrenomClient')
            ->add('AdresseClient')
            ->add('PhoneClient')
            ->add('OptionF')
            ->add('NbrMoisOF')
            ->add('Reference')
            ->add('Formule')
            ->add('NbrMois')
            ->add('Statut')
            ->add('FinRea')
            ->add('createdAt')
            ->add('updatedAt')
            ->add('user')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Recrutements::class,
        ]);
    }
}

src/Controller/RecrutementsController.php
<?php

namespace App\Controller;

use App\Entity\Rapports;
use App\Entity\Recrutements;
use App\Entity\Reabonnements;
use App\Form\RecrutementsType;
use App\Repository\StocksRepository;
use App\Repository\RapportsRepository;
use App\Repository\DecodeursRepository;
use Doctrine\ORM\EntityManagerInterface;
use App\Repository\RecrutementsRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

/**
 * @Route("/dashboard/recrutements")
 */
class RecrutementsController extends AbstractController
{
    /**
     * @Route("/", name="app_recrutements_index", methods={"GET"})
     */
    public function index(RecrutementsRepository $recrutementsRepository): Response
    {
        return $this->render('recrutements/index.html.twig', [
            'recrutements' => $recrutementsRepository->findBy(['user' => $this->getUser()], ['id' => 'DESC']),
        ]);
    }

    /**
     * @Route("/new", name="app_recrutements_new", methods={"GET", "POST"})
     */
    public function new(Request $request, RapportsRepository $rapportsRepository, RecrutementsRepository $recrutementsRepository, EntityManagerInterface $entityManager, StocksRepository $stocksRepository, DecodeursRepository $decodeursRepository): Response
    {
        $recrutement = new Recrutements();
        $user = $this->getUser();
        $stocks = $stocksRepository->findAll(['user' => $user->getSocietes()]);

        if ($request->isMethod('POST')) {
            $submittedToken = $request->request->get('Rectoken');
            if($this->isCsrfTokenValid('add-rec', $submittedToken)){

                if ($request->request->get('nopt')) {
                    $nopt = $request->request->get('nopt');
                } else {
                    $nopt = 0;
                }

                if($request->request->get('formule') == "Access"){
                    $montantF = 5000 ;
                } elseif ($request->request->get('formule') == "Evasion") {
                    $montantF = 9800 ;
                } elseif ($request->request->get('formule') == "Access +") {
                    $montantF = 15000 ;
                } elseif ($request->request->get('formule') == "Evasion +") {
                    $montantF = 20000 ;
                } elseif ($request->request->get('formule') == "Tout Canal +") {
                    $montantF = 40000 ;
                }

                $decodeur = $decodeursRepository->findOneBy(['numero' => $request->request->get('decodeur')]);
                $PD = 5000;
                $montant = $montantF + $PD ;

                $recrutement->setMontant($montant);
                if ($user->getSolde() >= $montant) {

                    $user->setSolde($user->getSolde() - ($montant - 1000));
                    $entityManager->persist($user);
                    $entityManager->flush();
                    
                    $recrutement->setNomClient($request->request->get('nom'));
                    $recrutement->setPrenomClient($request->request->get('prenom'));
                    $recrutement->setPhoneClient($request->request->get('phone'));
                    $recrutement->setAdresseClient($request->request->get('quartier'));
                    $recrutement->setReference($request->request->get('decodeur'));
                    $recrutement->setFormule($request->request->get('formule'));
                    $recrutement->setUser($user);
                    $recrutement->setStatut(false);
                    $entityManager->persist($recrutement);
                    $entityManager->flush();

                    $decodeur->setStatut(true);
                    $entityManager->persist($decodeur);
                    $entityManager->flush();

                    $rapport = $rapportsRepository->findBy([], ['id' => 'DESC'], $limit=1);
                    if ($rapport) {
                        $dateR = $rapport[0]->getCreatedAt();
                        $now = date("Y/m/d");
                        if ($now == $dateR->format("Y/m/d") ) {
                            $NbrRec = $rapport[0]->getNbrRec() + 1 ;
                            $MontantRec = $rapport[0]->getMontantRec() + $montant ;
                            $rapport[0]->setNbrRec($NbrRec);
                            $rapport[0]->setMontantRec($MontantRec);
                            $entityManager->persist($rapport[0]);
                            $entityManager->flush();
                        } else {
                            $rapport = new Rapports();
                            $rapport->setNbrRec(1);
                            $rapport->setMontantRec($montant);
                            $entityManager->persist($rapport);
                            $entityManager->flush();
                        }
                    } else {
                        $rapport = new Rapports();
                        $rapport->setNbrRec(1);
                        $rapport->setMontantRec($montant);
                        $entityManager->persist($rapport);
                        $entityManager->flush();
                    }

                    $this->addFlash(
                        'success',
                        'Recrutement lancé. En attente de validation !'
                     );
                    return $this->redirectToRoute('app_recrutements_index', [], Response::HTTP_SEE_OTHER);
                } else {
                    $this->addFlash(
                       'warning',
                       'Fonds Insuffisant ! Veuillez contact votre administrateur '
                    );
                    return $this->redirectToRoute('app_recrutements_new', [], Response::HTTP_SEE_OTHER);
                }

            }
        }

        return $this->renderForm('recrutements/new.html.twig', [
            'recrutement' => $recrutement,
            'stocks' => $stocks,
        ]);
    }

    /**
     * @Route("/{id}", name="app_recrutements_show", methods={"GET"})
     */
    public function show(Recrutements $recrutement): Response
    {
        return $this->render('recrutements/show.html.twig', [
            'recrutement' => $recrutement,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_recrutements_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Recrutements $recrutement, RecrutementsRepository $recrutementsRepository): Response
    {
        $form = $this->createForm(RecrutementsType::class, $recrutement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $recrutementsRepository->add($recrutement, true);

            return $this->redirectToRoute('app_recrutements_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('recrutements/edit.html.twig', [
            'recrutement' => $recrutement,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_recrutements_delete", methods={"POST"})
     */
    public function delete(Request $request, Recrutements $recrutement, RecrutementsRepository $recrutementsRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$recrutement->getId(), $request->request->get('_token'))) {
            $recrutementsRepository->remove($recrutement, true);
        }

        return $this->redirectToRoute('app_recrutements_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/recrutements/_delete_form.html.twig
<form method="post" action="{{ path('app_recrutements_delete', {'id': recrutement.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ recrutement.id) }}">
    <button class="btn">Delete</button>
</form>

templates/recrutements/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/recrutements/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Recrutements{% endblock %}

{% block body %}
    <h1>Edit Recrutements</h1>

    {{ include('recrutements/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_recrutements_index') }}">back to list</a>

    {{ include('recrutements/_delete_form.html.twig') }}
{% endblock %}

templates/recrutements/index.html.twig
{% extends 'base.html.twig' %}

{% block title %} Liste des Recrutements || {{ parent() }}{% endblock %}

{% block navline %}
    <div class="col-4 col-xl-4 page-title">
        <h4 class="f-w-700">Dashboard</h4>
        <nav>
            <ol class="breadcrumb justify-content-sm-start align-items-center mb-0">
            <li class="breadcrumb-item"><a href="{{path('app_dash')}}"> <i data-feather="home"> </i></a></li>
            <li class="breadcrumb-item f-w-400">Recrutements</li>
            <li class="breadcrumb-item f-w-400 active">Liste</li>
            </ol>
        </nav>
    </div>
{% endblock %}

{% block body %}
    <!-- Container-fluid starts-->
          <div class="container-fluid">
            <div class="row">
              <!-- Zero Configuration  Starts-->
              <div class="col-sm-12">
                <div class="card">
                  <div class="card-header">
                    <h4>Liste des Recrutements</h4> <br />
                    <span> <a href="{{ path('app_recrutements_new') }}"> <button class="btn btn-primary"> <i class="fa fa-plus"></i> Nouveau Recrutement </button></a></span>
                  </div>
                  <div class="card-body">
                    <div class="dt-ext table-responsive theme-scrollbar">
                      <table class="display" id="show-hidden-row">
                        <thead>
                          <tr>
                            <th>Date</th>
                            <th>Référence</th>
                            <th>Téléphone</th>
                            <th>Mois/Formule</th>
                            <th>Fin Réa</th>
                            <th>Montant</th>
                            <th>Statut</th>
                          </tr>
                        </thead>
                        <tbody>
                          {% for recrutement in recrutements %}
                            <tr>
                              <td>{{ recrutement.updatedAt ? recrutement.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
                              <td><span class="badge badge-primary"> {{ recrutement.Reference }} </span></td>
                              <td>{{ recrutement.PhoneClient }}</td>
                              <td>{{ recrutement.NbrMois }} mois {{ recrutement.Formule }}</td>
                              <td>{{ recrutement.Montant }}</td>
                              <td>{{ recrutement.FinRea ? recrutement.FinRea|date('Y-m-d') : '' }}</td>
                              <td>
                                  {% if recrutement.Statut == true %}
                                      <span class="badge rounded-pill badge-success">Activé</span>
                                  {% else %}
                                      <span class="badge rounded-pill badge-danger">En cours</span>
                                  {% endif %}
                              </td>
                            </tr>
                          {% else %}
                            <tr>
                              <td colspan="12"> Pas d'enregistrement</td>
                            </tr>
                          {% endfor %}
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
              </div>
              <!-- Zero Configuration  Ends-->
            </div>
          </div>
          <!-- Container-fluid Ends-->
{% endblock %}

templates/recrutements/new.html.twig
{% extends 'base.html.twig' %}

{% block title %} Nouveau Recrutement || {{ parent() }} {% endblock %}

{% block javascripts %}

    <script type="text/javascript">
        const formule = {
            access: 5000,
            evasion: 10000,
            access_plus: 15000,
            evasion_plus: 20000,
            tout_canal: 40000
        }
        
        let currentFormuleMontant = 5000
        let currentDMontant = 10000
        let total = 0
        let total1 = currentFormuleMontant
        let total2 = 0

        let getFormule = document.querySelector(".formule")
        let getTotalFormule = document.querySelector(".totalFormule")
        getTotalFormule.innerHTML = total1
        {# getFormule.addEventListener("click", function(){
            alert("clique on formule select")
        }) #}
        getFormule.addEventListener("change", (e) => {
            console.log("formule :: ",e.target.value)
            if (e.target.value == "Access"){
                currentFormuleMontant = formule.access
            }
            else if (e.target.value == "Evasion"){
                currentFormuleMontant = formule.evasion
            }
            else if (e.target.value == "Access +"){
                currentFormuleMontant = formule.access_plus
            }
            else if (e.target.value == "Evasion +"){
                currentFormuleMontant = formule.evasion_plus
            }
            else if (e.target.value == "Tout Canal +"){
                currentFormuleMontant = formule.tout_canal
            }
            console.log("currentFormuleMontant : ", currentFormuleMontant)
            total1 = currentFormuleMontant
            getTotalFormule.innerHTML = total2 - total1
        })

        getOption.addEventListener("change", (e) => {
            console.log("cformule :: ",e.target.value)
            if (e.target.value == "Access"){
                currentCformuleMontant = cformule.caccess
            }
            else if (e.target.value == "Evasion"){
                currentCformuleMontant = cformule.cevasion
            }
            else if (e.target.value == "Access +"){
                currentCformuleMontant = cformule.caccess_plus
            }
            else if (e.target.value == "Evasion +"){
                currentCformuleMontant = cformule.cevasion_plus
            }
            else if (e.target.value == "Tout Canal +"){
                currentCformuleMontant = cformule.ctout_canal
            }
            console.log("currentCformuleMontant : ", currentCformuleMontant)
            total2 = currentCformuleMontant
            getTotalFormule.innerHTML = total2 - total1
        })

        {# if (total1>0 && total2>0){
            total = total1 + total2
            getTotalFormule.innerHTML = total
        } #}
        
        var inputQuantityTel = [];
        $(function() {
            $(".ntel").on("keyup", function (e) {
                var $field = $(this),
                val=this.value,
                $thisIndex=parseInt($field.data("idx"),11); 
                if (this.validity && this.validity.badInput || isNaN(val) || $field.is(":invalid") ) {
                    this.value = inputQuantityTel[$thisIndex];
                    return;
                } 
                if (val.length > Number($field.attr("maxlength"))) {
                    val=val.slice(0, 11);
                    $field.val(val);
                }
                inputQuantityTel[$thisIndex]=val;
            });
        });
    </script>
{% endblock %}

{% block navline %}
    <div class="col-4 col-xl-4 page-title">
        <h4 class="f-w-700">Dashboard</h4>
        <nav>
            <ol class="breadcrumb justify-content-sm-start align-items-center mb-0">
                <li class="breadcrumb-item"><a href="{{path('app_dash')}}"> <i data-feather="home"> </i></a></li>
                <li class="breadcrumb-item f-w-400">Recrutement</li>
                <li class="breadcrumb-item f-w-400 active">New Recrutement</li>
            </ol>
        </nav>
    </div>
{% endblock %}

{% block body %}
<!-- Container-fluid starts-->
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-header">
                <h4>Nouveau Recrutement</h4>
                <p class="f-m-light mt-1">Priez prendre le soins de bien remplir le formulaire.</p>
                </div>
                <div class="card-body custom-input">
                    <form class="row g-3" method="POST">
                        <div class="col-12 col-md-6 col-lg-4 col-xl-4"> 
                            <label class="form-label" for="nom">Nom Client</label>
                            <input class="form-control" id="nom" name="nom" type="text" placeholder="Nom Client" aria-label="Nom" required>
                        </div>
                        
                        <div class="col-12 col-md-6 col-lg-4 col-xl-4"> 
                            <label class="form-label" for="prenom">Prénom(s) Clients</label>
                            <input class="form-control" id="prenom" name="prenom" type="text" placeholder="Prénom(s) Clients" aria-label="Prénom(s) Clients" required>
                        </div>

                        <div class="col-12 col-md-6 col-lg-4 col-xl-4">
                            <label class="form-label" for="ntel">N° Téléphone</label>
                            <input class="form-control ntel" id="ntel" name="phone" type="tel" placeholder="22900000000"  min="0" max="22999999999" maxlength="11" required>
                        </div>

                        <div class="col-12 col-md-6 col-lg-4 col-xl-4">
                            <label class="form-label" for="quartier">Quartier</label>
                            <input class="form-control" id="quartier" name="quartier" type="text" placeholder="Quartier" required>
                        </div>

                        <div class="col-12 col-md-6 col-lg-4 col-xl-4">
                            <label class="form-label" for="decodeur">N° Décodeur</label>
                            <select class="form-select" id="entran" name="decodeur">
                                <option value="Choisir le décodeur" selected disabled> Choisir le décodeur</option>
                                {% for stock in stocks %}
                                    {% for decodeur in stock.decodeurs %}
                                        {% if decodeur.statut == false %}
                                            <option value="{{ decodeur.numero }}"> {{ decodeur.numero }} </option>
                                        {% endif %}
                                    {% endfor %}
                                {% endfor %}
                            </select>
                        </div>

                        <div class="col-12 col-md-6 col-lg-4 col-xl-4"> 
                            <label class="form-label" for="C63195">Choix Formule</label>
                            <select class="form-select formule" id="C63195" name="formule" required="" >
                                <option value="Access"> Access </option>
                                <option value="Evasion"> Evasion </option>
                                <option value="Access +"> Access + </option>
                                <option value="Evasion +"> Evasion + </option>
                                <option value="Tout Canal +"> Tout Canal + </option>
                            </select>
                        </div>

                        <div class="col-12"> 
                            <label class="form-label" for="exampleFormControlTextarea1">Observation</label>
                            <textarea class="form-control" id="exampleFormControlTextarea1" name="observation" rows="3"></textarea>
                        </div>

                        <div class="col-12"> 
                            <div class="form-check form-switch">
                                <input class="form-check-input" id="flexSwitchCheckDefault" type="checkbox" role="switch" required>
                                <label class="form-check-label" for="flexSwitchCheckDefault">Êtes-vous sûr que les informations ci-dessus sont vraies ?</label>
                            </div>
                        </div>
                        <input type="hidden" name="Rectoken" value="{{ csrf_token('add-rec') }}">
                        <div class="col-12">
                            <button class="btn btn-primary" type="submit">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Container-fluid Ends-->
{% endblock %}

templates/recrutements/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Recrutements{% endblock %}

{% block body %}
    <h1>Recrutements</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ recrutement.id }}</td>
            </tr>
            <tr>
                <th>NomClient</th>
                <td>{{ recrutement.NomClient }}</td>
            </tr>
            <tr>
                <th>PrenomClient</th>
                <td>{{ recrutement.PrenomClient }}</td>
            </tr>
            <tr>
                <th>AdresseClient</th>
                <td>{{ recrutement.AdresseClient }}</td>
            </tr>
            <tr>
                <th>PhoneClient</th>
                <td>{{ recrutement.PhoneClient }}</td>
            </tr>
            <tr>
                <th>OptionF</th>
                <td>{{ recrutement.OptionF }}</td>
            </tr>
            <tr>
                <th>NbrMoisOF</th>
                <td>{{ recrutement.NbrMoisOF }}</td>
            </tr>
            <tr>
                <th>Reference</th>
                <td>{{ recrutement.Reference }}</td>
            </tr>
            <tr>
                <th>Formule</th>
                <td>{{ recrutement.Formule }}</td>
            </tr>
            <tr>
                <th>NbrMois</th>
                <td>{{ recrutement.NbrMois }}</td>
            </tr>
            <tr>
                <th>Statut</th>
                <td>{{ recrutement.Statut }}</td>
            </tr>
            <tr>
                <th>FinRea</th>
                <td>{{ recrutement.FinRea ? recrutement.FinRea|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>CreatedAt</th>
                <td>{{ recrutement.createdAt ? recrutement.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>UpdatedAt</th>
                <td>{{ recrutement.updatedAt ? recrutement.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_recrutements_index') }}">back to list</a>

    <a href="{{ path('app_recrutements_edit', {'id': recrutement.id}) }}">edit</a>

    {{ include('recrutements/_delete_form.html.twig') }}
{% endblock %}