src/Entity/Users.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\UsersRepository;
use App\Entity\Traits\Timestampable;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;

/**
 * @ORM\Entity(repositoryClass=UsersRepository::class)
 * @ORM\HasLifecycleCallbacks
 * @UniqueEntity(fields={"username"}, message="There is already an account with this username")
 */
class Users implements UserInterface, PasswordAuthenticatedUserInterface
{
    use Timestampable;
    
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $username;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Prenoms;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Phone;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Adresse;

    /**
     * @ORM\Column(type="boolean")
     */
    private $Sexe;

    /**
     * @ORM\ManyToOne(targetEntity=Societes::class, inversedBy="user")
     */
    private $societes;

    /**
     * @ORM\OneToMany(targetEntity=Migrations::class, mappedBy="user")
     */
    private $migrations;

    /**
     * @ORM\OneToMany(targetEntity=Reabonnements::class, mappedBy="User")
     */
    private $reabonnements;

    /**
     * @ORM\OneToMany(targetEntity=Recrutements::class, mappedBy="user")
     */
    private $recrutements;

    /**
     * @ORM\OneToMany(targetEntity=Complements::class, mappedBy="User")
     */
    private $complements;

    /**
     * @ORM\Column(type="float")
     */
    private $Solde;

    /**
     * @ORM\OneToMany(targetEntity=Commissions::class, mappedBy="user")
     */
    private $commissions;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $commission;

    /**
     * @ORM\OneToMany(targetEntity=Recharges::class, mappedBy="user")
     */
    private $recharges;

    /**
     * @ORM\OneToMany(targetEntity=Stocks::class, mappedBy="admi")
     */
    private $stocks;

    /**
     * @ORM\OneToMany(targetEntity=Decodeurs::class, mappedBy="user")
     */
    private $decodeurs;

    public function __construct()
    {
        $this->migrations = new ArrayCollection();
        $this->reabonnements = new ArrayCollection();
        $this->recrutements = new ArrayCollection();
        $this->complements = new ArrayCollection();
        $this->commissions = new ArrayCollection();
        $this->recharges = new ArrayCollection();
        $this->stocks = new ArrayCollection();
        $this->decodeurs = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->username;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenoms(): ?string
    {
        return $this->Prenoms;
    }

    public function setPrenoms(string $Prenoms): self
    {
        $this->Prenoms = $Prenoms;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->Email;
    }

    public function setEmail(string $Email): self
    {
        $this->Email = $Email;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->Phone;
    }

    public function setPhone(string $Phone): self
    {
        $this->Phone = $Phone;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->Adresse;
    }

    public function setAdresse(string $Adresse): self
    {
        $this->Adresse = $Adresse;

        return $this;
    }

    public function isSexe(): ?bool
    {
        return $this->Sexe;
    }

    public function setSexe(bool $Sexe): self
    {
        $this->Sexe = $Sexe;

        return $this;
    }

    public function getSocietes(): ?Societes
    {
        return $this->societes;
    }

    public function setSocietes(?Societes $societes): self
    {
        $this->societes = $societes;

        return $this;
    }

    /**
     * @return Collection<int, Migrations>
     */
    public function getMigrations(): Collection
    {
        return $this->migrations;
    }

    public function addMigration(Migrations $migration): self
    {
        if (!$this->migrations->contains($migration)) {
            $this->migrations[] = $migration;
            $migration->setUser($this);
        }

        return $this;
    }

    public function removeMigration(Migrations $migration): self
    {
        if ($this->migrations->removeElement($migration)) {
            // set the owning side to null (unless already changed)
            if ($migration->getUser() === $this) {
                $migration->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Reabonnements>
     */
    public function getReabonnements(): Collection
    {
        return $this->reabonnements;
    }

    public function addReabonnement(Reabonnements $reabonnement): self
    {
        if (!$this->reabonnements->contains($reabonnement)) {
            $this->reabonnements[] = $reabonnement;
            $reabonnement->setUser($this);
        }

        return $this;
    }

    public function removeReabonnement(Reabonnements $reabonnement): self
    {
        if ($this->reabonnements->removeElement($reabonnement)) {
            // set the owning side to null (unless already changed)
            if ($reabonnement->getUser() === $this) {
                $reabonnement->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Recrutements>
     */
    public function getRecrutements(): Collection
    {
        return $this->recrutements;
    }

    public function addRecrutement(Recrutements $recrutement): self
    {
        if (!$this->recrutements->contains($recrutement)) {
            $this->recrutements[] = $recrutement;
            $recrutement->setUser($this);
        }

        return $this;
    }

    public function removeRecrutement(Recrutements $recrutement): self
    {
        if ($this->recrutements->removeElement($recrutement)) {
            // set the owning side to null (unless already changed)
            if ($recrutement->getUser() === $this) {
                $recrutement->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Complements>
     */
    public function getComplements(): Collection
    {
        return $this->complements;
    }

    public function addComplement(Complements $complement): self
    {
        if (!$this->complements->contains($complement)) {
            $this->complements[] = $complement;
            $complement->setUser($this);
        }

        return $this;
    }

    public function removeComplement(Complements $complement): self
    {
        if ($this->complements->removeElement($complement)) {
            // set the owning side to null (unless already changed)
            if ($complement->getUser() === $this) {
                $complement->setUser(null);
            }
        }

        return $this;
    }

    public function getSolde(): ?float
    {
        return $this->Solde;
    }

    public function setSolde(float $Solde): self
    {
        $this->Solde = $Solde;

        return $this;
    }

    /**
     * @return Collection<int, Commissions>
     */
    public function getCommissions(): Collection
    {
        return $this->commissions;
    }

    public function addCommission(Commissions $commission): self
    {
        if (!$this->commissions->contains($commission)) {

src/Form/UsersType.php
<?php

namespace App\Form;

use App\Entity\Users;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UsersType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('username')
            ->add('roles')
            ->add('password')
            ->add('Nom')
            ->add('Prenoms')
            ->add('Email')
            ->add('Phone')
            ->add('Adresse')
            ->add('Sexe')
            ->add('createdAt')
            ->add('updatedAt')
            ->add('societes')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Users::class,
        ]);
    }
}

templates/users/_delete_form.html.twig
<form method="post" action="{{ path('app_users_delete', {'id': user.id}) }}" onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer ce partenaire ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn">Supprimer</button>
</form>

templates/users/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Users{% endblock %}

{% block body %}
    <h1>Edit Users</h1>

    {{ include('users/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_users_index') }}">back to list</a>

    {{ include('users/_delete_form.html.twig') }}
{% endblock %}

templates/users/index.html.twig
{% extends 'base-admin.html.twig' %}

{% block title %} Liste des Partenaires || {{ parent() }}{% endblock %}

{% block navline %}
    <div class="col-4 col-xl-4 page-title">
        <h4 class="f-w-700">Dashboard</h4>
        <nav>
            <ol class="breadcrumb justify-content-sm-start align-items-center mb-0">
            <li class="breadcrumb-item"><a href="{{path('app_dash')}}"> <i data-feather="home"> </i></a></li>
            <li class="breadcrumb-item f-w-400">Partenaires</li>
            <li class="breadcrumb-item f-w-400 active">Liste</li>
            </ol>
        </nav>
    </div>
{% endblock %}

{% block body %}
    <!-- Container-fluid starts-->
          <div class="container-fluid">
            <div class="row">
              <!-- Zero Configuration  Starts-->
              <div class="col-sm-12">
                <div class="card">
                  <div class="card-header">
                    <h4>Liste des Partenaires</h4> <br />
                    <span> <a href="{{ path('app_users_new') }}"> <button class="btn btn-primary"> <i class="fa fa-plus"></i> Nouveau Partenaire </button></a></span>
                  </div>
                  <div class="card-body">
                    <div class="table-responsive theme-scrollbar">
                      <table class="display" id="basic-1">
                        <thead>
                          <tr>
                            <th>Nom & Prénoms</th>
                            <th>Username</th>
                            <th>Téléphone</th>
                            <th>Email</th>
                            <th>Adresse</th>
                            <th>Société</th>
                            <th>Solde</th>
                            <th>Date d'ajout</th>
                            <th>Action</th>
                          </tr>
                        </thead>
                        <tbody>
                            {% for user in users %}
                                <tr>
                                    <td>{{ user.Nom }} {{ user.Prenoms }}</td>
                                    <td>{{ user.username }}</td>
                                    <td>{{ user.Phone }}</td>
                                    <td>{{ user.Email }}</td>
                                    <td>{{ user.Adresse }}</td>
                                    <td>{{ user.societes.Nom }}</td>
                                    <td>{{ user.solde }}</td>
                                    <td>{{ user.createdAt ? user.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                                    <td>
                                        <ul class="action"> 
                                            <li class="edit"> <a href="#"><i class="icon-pencil-alt"></i></a></li>
                                            <li class="delete"><a href="{{ path('app_users_delete', {'id': user.id}) }}"><i class="icon-trash"></i></a></li>
                                        </ul>
                                    </td>
                                </tr>
                            {% else %}
                                <tr>
                                    <td colspan="13">no records found</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
              </div>
              <!-- Zero Configuration  Ends-->
            </div>
          </div>
          <!-- Container-fluid Ends-->

        <!-- Modal Solde-->
        <div class="modal fade" id="exampleModallogin" tabindex="-1" role="dialog" aria-labelledby="exampleModallogin" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content dark-sign-up">
              <div class="modal-body social-profile text-start">
                <div class="modal-toggle-wrapper">
                  <h4 class="text-dark">Ajout de Solde</h4>
                  <p>Please check the information entered before confirming.</p>
                  <form class="row g-3" method="post" action="{{ path('app_ajsolde') }}">
                    <div class="col-md-12">
                      <label class="form-label" for="entran">Sociéte</label>
                      <select class="form-select js-select-single" id="entran" name="id">
                        {% for societe in societes %}
                            <option value="{{ societe.id }}"> {{ societe.Nom }} </option>
                        {% endfor %}
                      </select>
                    </div>
                    <div class="col-md-12">
                      <label class="form-label" for="inputer">Montant</label>
                      <input class="form-control" id="inputer" type="float" name="solde" placeholder="Entrer le montant à recharger">
                    </div>
                    <input type="hidden" name="Stoken" value="{{ csrf_token('add-solde') }}">
                    <div class="col-12">
                      <button class="btn btn-primary" type="submit" data-bs-dismiss="modal">Recharger</button>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- Modal Solde-->
{% endblock %}

templates/users/new.html.twig
{% extends 'base-admin.html.twig' %}

{% block title %} Nouveau Utilisateur || {{ parent() }} {% endblock %}

{% block stylesheets %}
    <style>
        /* Text states (for js) */
        .hide {
            opacity: 0;
            top: calc(50% + 8em);
            display:none;
        }
        .show {
            opacity: 1;
            top: calc(50% + 6em);
        }
    </style>
{% endblock %}

{% block javascripts %}
    <script type="text/javascript">
        var password = document.getElementById('fakePassword');
          var toggler = document.getElementById('toggler');
    
          showHidePassword = () => {
            if (password.type == 'password') {
              password.setAttribute('type', 'text');
              toggler.classList.add('fa-eye-slash');
            } else {
              password.setAttribute('type', 'password');
            }
          };
    
          toggler.addEventListener('click', showHidePassword);
    </script>
    <script type="text/javascript">
        $(function() {
            $("#CAT_Custom_20063195").change(function() {
                if ($("#otherSelect").is(":selected")) {
                $(".moreInfoShow").show();
                } else {
                $(".moreInfoShow").hide();
                }
            }).trigger('change');
        });
    </script>
    
    <script type="text/javascript">
        var password = document.getElementById("password")
        , confirm_password = document.getElementById("confirm_password");

        function validatePassword(){
            if(password.value != confirm_password.value) {
                confirm_password.setCustomValidity("Passwords Don't Match");
            } else {
                confirm_password.setCustomValidity('');
            }
        }

        password.onchange = validatePassword;
        confirm_password.onkeyup = validatePassword;
    </script>
    <script type="text/javascript">
        $(document).ready(function() {
            $(".js-select2").select2({
                closeOnSelect: true
            });
        });
    </script>
{% endblock %}

{% block navline %}
    <div class="col-4 col-xl-4 page-title">
        <h4 class="f-w-700">Dashboard</h4>
        <nav>
            <ol class="breadcrumb justify-content-sm-start align-items-center mb-0">
            <li class="breadcrumb-item"><a href="{{path('app_dash')}}"> <i data-feather="home"> </i></a></li>
            <li class="breadcrumb-item f-w-400">Partenaires</li>
            <li class="breadcrumb-item f-w-400 active">Ajout Partenaire</li>
            </ol>
        </nav>
    </div>
{% endblock %}

{% block body %}
<!-- Container-fluid starts-->
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-header">
                <h4>Ajouts de partenaire</h4>
                <p class="f-m-light mt-1">Priez prendre le soins de bien remplir le formulaire.</p>
                </div>
                <div class="card-body custom-input">
                    <form class="row g-3" method="POST">
                        <div class="col-6"> 
                            <label class="form-label" for="first-name">Prénoms</label>
                            <input class="form-control" id="first-name" name="prenom" type="text" placeholder="Prénoms" aria-label="First name" required>
                        </div>
                        
                        <div class="col-6"> 
                            <label class="form-label" for="last-name">Nom</label>
                            <input class="form-control" id="last-name" name="nom" type="text" placeholder="Nom" aria-label="First name" required>
                        </div>
                        
                        <div class="col-6">
                            <label class="form-label" for="exampleFormControlInput1">Email address</label>
                            <input class="form-control" id="exampleFormControlInput1" name="email" type="email" placeholder="pesamof475@saeoil.com" required>
                        </div>

                        <div class="col-6">
                            <label class="form-label" for="Input1">Téléphone</label>
                            <input class="form-control" id="Input1" name="phone" type="tel" placeholder="22900000000" required>
                        </div>

                        <div class="col-6"> 
                            <label class="form-label" for="adresse">Adresse</label>
                            <input class="form-control" id="adresse" name="adresse" type="text" placeholder="Adresse" aria-label="Adresse" required>
                        </div>

                        <div class="col-6"> 
                            <label class="form-label" for="genre">Genre</label>
                            <div class="card-wrapper border rounded-3 checkbox-checked">
                                <div class="radio-form">
                                    <div class="form-check">
                                        <input class="form-check-input" id="flexRadioDefault1" type="radio" name="genre" value="Femme" required="">
                                        <label class="form-check-label" for="flexRadioDefault1">Femme</label>
                                    </div>
                                    <div class="form-check">
                                        <input class="form-check-input" id="flexRadioDefault2" type="radio" name="genre" value="Homme" required="">
                                        <label class="form-check-label" for="flexRadioDefault2">Homme</label>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-6"> 
                            <label class="form-label" for="CAT_Custom_20063195">Choix Société</label>
                            <select class="form-select js-select2" id="CAT_Custom_20063195" name="societe" required="" >
                                <option selected="" disabled="" value="">Choose...</option>
                                <option id="otherSelect" class="btn btn-secondary btn-clipboard" value="new">Nouvelle Société</option>
                                {% for societe in societes %}
                                    <option value="{{ societe.id }}"> {{ societe.Nom }} </option>
                                {% endfor %}
                            </select>
                        </div>

                        <div class="row g-3 moreInfoShow">
                            <div class="row g-3">
                                <div class="col-6"> 
                                    <label class="form-label" for="so-name">Nom de la société</label>
                                    <input class="form-control" id="so-name" name="so-name" type="text" placeholder="Nom de la société" aria-label="Nom de la société">
                                </div>

                                <div class="col-6"> 
                                    <label class="form-label" for="example1">Domaine d'Activité</label>
                                    <textarea class="form-control" id="example1" name="secAct" rows="3"></textarea>
                                </div>

                                <div class="col-6">
                                    <label class="form-label" for="departement">Département</label>
                                    <input class="form-control" id="departement" name="departement" type="text" placeholder="Département">
                                </div>

                                <div class="col-6">
                                    <label class="form-label" for="commune">Commune</label>
                                    <input class="form-control" id="commune" name="commune" type="text" placeholder="Commune">
                                </div>

                                <div class="col-6"> 
                                    <label class="form-label" for="Quartier">Quartier</label>
                                    <input class="form-control" id="Quartier" name="quartier" type="text" placeholder="Quartier">
                                </div>

                                <div class="col-6"> 
                                    <label class="form-label" for="adSo">Adresse Société</label>
                                    <input class="form-control" id="adSo" name="adsocie" type="text" placeholder="Adresse Société">
                                </div>

                                <div class="col-6">
                                    <label class="form-label" for="latitude">Latitude</label>
                                    <input class="form-control" id="latitude" name="latitude" type="text" placeholder="Latitude">
                                </div>

                                <div class="col-6">
                                    <label class="form-label" for="longitude">Longitude</label>
                                    <input class="form-control" id="longitude" name="longitude" type="text" placeholder="Longitude">
                                </div>
                            </div>
                        </div>

                        <div class="col-6"> 
                            <label class="form-label" for="identifiant">Identifiant</label>
                            <input class="form-control" id="identifiant" name="identifiant" type="text" placeholder="Identifiant" aria-label="Identifiant" required>
                        </div>

                        <div class="col-6"> 
                            <label class="col-sm-12 col-form-label" for="password">Password</label>
                            <input class="form-control" id="password" name="password" type="password" id="fakePassword"  required>
                            <span><i id="toggler"class="fa fa-fw fa-eye-slash show-hide"></i></span>
                        </div>

                        <div class="col-6"> 
                            <label class="col-sm-12 col-form-label" for="confirm_password">Confirmation Password</label>
                            <input class="form-control" id="confirm_password" name="cpassword" type="password" required>
                        </div>

                        <div class="col-12"> 
                            <label class="form-label" for="exampleFormControlTextarea1">Observation</label>
                            <textarea class="form-control" id="exampleFormControlTextarea1" name="observation" rows="3"></textarea>
                        </div>

                        <div class="col-12"> 
                            <div class="form-check form-switch">
                                <input class="form-check-input" id="flexSwitchCheckDefault" type="checkbox" role="switch" required>
                                <label class="form-check-label" for="flexSwitchCheckDefault">Êtes-vous sûr que les informations ci-dessus sont vraies ?</label>
                            </div>
                        </div>
                        <input type="hidden" name="Utoken" value="{{ csrf_token('add-user') }}">
                        <div class="col-12">
                            <button class="btn btn-primary" type="submit">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Container-fluid Ends-->
{% endblock %}